host:
  address: 0.0.0.0
  port: 8080

flags:
  debug_mode: true
  threaded: true

vars:
  static_url_path: /static
  static_folder: ../static
  template_folder: ../layouts
  strawberry_id_domain: https://id.strawberryfoundations.xyz/v1/
  mail_tld: strawberryfoundations.xyz

mail:
  smtp_host: mail.strawberryfoundations.xyz
  smtp_port: 587

  imap_host: mail.strawberryfoundations.xyz
  imap_port: 993  # Imap Port, usually 993